### ISSUE TITLE
Not able to register my hue bridge

### ISSUE THREAD

**Issue by mrpajzl** [pixelspark/huejs#10]
Hi, I'm trying to run this app but I'm not able to register my bridge. It asks for IP and username but I have no idea what is my username

**Comment by mrpajzl** [comment]
BTW I understand this is an old project but it seems to me as a brilliant idea and I would love to get it working / possibly update it to be more recent and working so if you have some tips or trics that I could use please send them and I will create PR with my updates

**Comment by pixelspark** [comment]
If you don't have a user name yet, simply click the button on the Bridge to put it in 'register' mode, fill in the IP address of the bridge, and click 'register'. A user name should be generated and appear in the user name field. Save the user name as you will be able to use the bridge with it from then on.

**Comment by mrpajzl** [comment]
Thanks
